/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResponsibleGamblingRouteImport } from './routes/responsible-gambling'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountHistoryRouteImport } from './routes/account.history'
import { Route as AccountLimitsRouteImport } from './routes/account.limits'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as AccountSecurityRouteImport } from './routes/account.security'
import { Route as AccountVerificationRouteImport } from './routes/account.verification'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminReviewsIndexRouteImport } from './routes/admin.reviews.index'
import { Route as AdminReviewsIdRouteImport } from './routes/admin.reviews.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsibleGamblingRoute = ResponsibleGamblingRouteImport.update({
  id: '/responsible-gambling',
  path: '/responsible-gambling',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountHistoryRoute = AccountHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AccountRoute,
} as any)
const AccountLimitsRoute = AccountLimitsRouteImport.update({
  id: '/limits',
  path: '/limits',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSecurityRoute = AccountSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AccountRoute,
} as any)
const AccountVerificationRoute = AccountVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => AccountRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsIndexRoute = AdminReviewsIndexRouteImport.update({
  id: '/reviews/',
  path: '/reviews/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsIdRoute = AdminReviewsIdRouteImport.update({
  id: '/reviews/$id',
  path: '/reviews/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/responsible-gambling': typeof ResponsibleGamblingRoute
  '/terms': typeof TermsRoute
  '/account/history': typeof AccountHistoryRoute
  '/account/limits': typeof AccountLimitsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/verification': typeof AccountVerificationRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/reviews/$id': typeof AdminReviewsIdRoute
  '/admin/reviews/': typeof AdminReviewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/responsible-gambling': typeof ResponsibleGamblingRoute
  '/terms': typeof TermsRoute
  '/account/history': typeof AccountHistoryRoute
  '/account/limits': typeof AccountLimitsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/verification': typeof AccountVerificationRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/reviews/$id': typeof AdminReviewsIdRoute
  '/admin/reviews': typeof AdminReviewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/responsible-gambling': typeof ResponsibleGamblingRoute
  '/terms': typeof TermsRoute
  '/account/history': typeof AccountHistoryRoute
  '/account/limits': typeof AccountLimitsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/verification': typeof AccountVerificationRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/reviews/$id': typeof AdminReviewsIdRoute
  '/admin/reviews/': typeof AdminReviewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/register'
    | '/responsible-gambling'
    | '/terms'
    | '/account/history'
    | '/account/limits'
    | '/account/profile'
    | '/account/security'
    | '/account/verification'
    | '/admin/audit'
    | '/admin/settings'
    | '/admin/users'
    | '/account/'
    | '/admin/'
    | '/admin/reviews/$id'
    | '/admin/reviews/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/register'
    | '/responsible-gambling'
    | '/terms'
    | '/account/history'
    | '/account/limits'
    | '/account/profile'
    | '/account/security'
    | '/account/verification'
    | '/admin/audit'
    | '/admin/settings'
    | '/admin/users'
    | '/account'
    | '/admin'
    | '/admin/reviews/$id'
    | '/admin/reviews'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/register'
    | '/responsible-gambling'
    | '/terms'
    | '/account/history'
    | '/account/limits'
    | '/account/profile'
    | '/account/security'
    | '/account/verification'
    | '/admin/audit'
    | '/admin/settings'
    | '/admin/users'
    | '/account/'
    | '/admin/'
    | '/admin/reviews/$id'
    | '/admin/reviews/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResponsibleGamblingRoute: typeof ResponsibleGamblingRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responsible-gambling': {
      id: '/responsible-gambling'
      path: '/responsible-gambling'
      fullPath: '/responsible-gambling'
      preLoaderRoute: typeof ResponsibleGamblingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/history': {
      id: '/account/history'
      path: '/history'
      fullPath: '/account/history'
      preLoaderRoute: typeof AccountHistoryRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/limits': {
      id: '/account/limits'
      path: '/limits'
      fullPath: '/account/limits'
      preLoaderRoute: typeof AccountLimitsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/security': {
      id: '/account/security'
      path: '/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AccountSecurityRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/verification': {
      id: '/account/verification'
      path: '/verification'
      fullPath: '/account/verification'
      preLoaderRoute: typeof AccountVerificationRouteImport
      parentRoute: typeof AccountRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews/': {
      id: '/admin/reviews/'
      path: '/reviews'
      fullPath: '/admin/reviews/'
      preLoaderRoute: typeof AdminReviewsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews/$id': {
      id: '/admin/reviews/$id'
      path: '/reviews/$id'
      fullPath: '/admin/reviews/$id'
      preLoaderRoute: typeof AdminReviewsIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AccountRouteChildren {
  AccountHistoryRoute: typeof AccountHistoryRoute
  AccountLimitsRoute: typeof AccountLimitsRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountSecurityRoute: typeof AccountSecurityRoute
  AccountVerificationRoute: typeof AccountVerificationRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountHistoryRoute: AccountHistoryRoute,
  AccountLimitsRoute: AccountLimitsRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountSecurityRoute: AccountSecurityRoute,
  AccountVerificationRoute: AccountVerificationRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminReviewsIdRoute: typeof AdminReviewsIdRoute
  AdminReviewsIndexRoute: typeof AdminReviewsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminReviewsIdRoute: AdminReviewsIdRoute,
  AdminReviewsIndexRoute: AdminReviewsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResponsibleGamblingRoute: ResponsibleGamblingRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
