/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AmlRouteImport } from './routes/aml'
import { Route as ApostasRouteImport } from './routes/apostas'
import { Route as BonusRouteImport } from './routes/bonus'
import { Route as BorabetRouteImport } from './routes/borabet'
import { Route as CarteiraRouteImport } from './routes/carteira'
import { Route as CassinoRouteImport } from './routes/cassino'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as DesafiosRouteImport } from './routes/desafios'
import { Route as EsportesRouteImport } from './routes/esportes'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PesquisaRouteImport } from './routes/pesquisa'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PromocoesRouteImport } from './routes/promocoes'
import { Route as RecompensasRouteImport } from './routes/recompensas'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RegrasApostasRouteImport } from './routes/regras-apostas'
import { Route as ResponsibleGamblingRouteImport } from './routes/responsible-gambling'
import { Route as RoletaRouteImport } from './routes/roleta'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VipRouteImport } from './routes/vip'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountHistoryRouteImport } from './routes/account.history'
import { Route as AccountLimitsRouteImport } from './routes/account.limits'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as AccountSecurityRouteImport } from './routes/account.security'
import { Route as AccountVerificationRouteImport } from './routes/account.verification'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as CarteiraIndexRouteImport } from './routes/carteira.index'
import { Route as CarteiraDepositoRouteImport } from './routes/carteira.deposito'
import { Route as CarteiraSaqueRouteImport } from './routes/carteira.saque'
import { Route as CarteiraTransacoesRouteImport } from './routes/carteira.transacoes'
import { Route as CassinoIndexRouteImport } from './routes/cassino.index'
import { Route as CassinoAoVivoRouteImport } from './routes/cassino.ao-vivo'
import { Route as CassinoCrashRouteImport } from './routes/cassino.crash'
import { Route as CassinoOriginaisRouteImport } from './routes/cassino.originais'
import { Route as CassinoSlotsRouteImport } from './routes/cassino.slots'
import { Route as EsportesIndexRouteImport } from './routes/esportes.index'
import { Route as EsportesAoVivoRouteImport } from './routes/esportes.ao-vivo'
import { Route as EsportesProximosRouteImport } from './routes/esportes.proximos'
import { Route as PromocoesIndexRouteImport } from './routes/promocoes.index'
import { Route as PromocoesIdRouteImport } from './routes/promocoes.$id'
import { Route as AdminReviewsIndexRouteImport } from './routes/admin.reviews.index'
import { Route as AdminReviewsIdRouteImport } from './routes/admin.reviews.$id'
import { Route as CassinoJogoIdRouteImport } from './routes/cassino.jogo.$id'
import { Route as EsportesEventoIdRouteImport } from './routes/esportes.evento.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AmlRoute = AmlRouteImport.update({
  id: '/aml',
  path: '/aml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApostasRoute = ApostasRouteImport.update({
  id: '/apostas',
  path: '/apostas',
  getParentRoute: () => rootRouteImport,
} as any)
const BonusRoute = BonusRouteImport.update({
  id: '/bonus',
  path: '/bonus',
  getParentRoute: () => rootRouteImport,
} as any)
const BorabetRoute = BorabetRouteImport.update({
  id: '/borabet',
  path: '/borabet',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteiraRoute = CarteiraRouteImport.update({
  id: '/carteira',
  path: '/carteira',
  getParentRoute: () => rootRouteImport,
} as any)
const CassinoRoute = CassinoRouteImport.update({
  id: '/cassino',
  path: '/cassino',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const DesafiosRoute = DesafiosRouteImport.update({
  id: '/desafios',
  path: '/desafios',
  getParentRoute: () => rootRouteImport,
} as any)
const EsportesRoute = EsportesRouteImport.update({
  id: '/esportes',
  path: '/esportes',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisaRoute = PesquisaRouteImport.update({
  id: '/pesquisa',
  path: '/pesquisa',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PromocoesRoute = PromocoesRouteImport.update({
  id: '/promocoes',
  path: '/promocoes',
  getParentRoute: () => rootRouteImport,
} as any)
const RecompensasRoute = RecompensasRouteImport.update({
  id: '/recompensas',
  path: '/recompensas',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RegrasApostasRoute = RegrasApostasRouteImport.update({
  id: '/regras-apostas',
  path: '/regras-apostas',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsibleGamblingRoute = ResponsibleGamblingRouteImport.update({
  id: '/responsible-gambling',
  path: '/responsible-gambling',
  getParentRoute: () => rootRouteImport,
} as any)
const RoletaRoute = RoletaRouteImport.update({
  id: '/roleta',
  path: '/roleta',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VipRoute = VipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountHistoryRoute = AccountHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AccountRoute,
} as any)
const AccountLimitsRoute = AccountLimitsRouteImport.update({
  id: '/limits',
  path: '/limits',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSecurityRoute = AccountSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AccountRoute,
} as any)
const AccountVerificationRoute = AccountVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => AccountRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const CarteiraIndexRoute = CarteiraIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CarteiraRoute,
} as any)
const CarteiraDepositoRoute = CarteiraDepositoRouteImport.update({
  id: '/deposito',
  path: '/deposito',
  getParentRoute: () => CarteiraRoute,
} as any)
const CarteiraSaqueRoute = CarteiraSaqueRouteImport.update({
  id: '/saque',
  path: '/saque',
  getParentRoute: () => CarteiraRoute,
} as any)
const CarteiraTransacoesRoute = CarteiraTransacoesRouteImport.update({
  id: '/transacoes',
  path: '/transacoes',
  getParentRoute: () => CarteiraRoute,
} as any)
const CassinoIndexRoute = CassinoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CassinoRoute,
} as any)
const CassinoAoVivoRoute = CassinoAoVivoRouteImport.update({
  id: '/ao-vivo',
  path: '/ao-vivo',
  getParentRoute: () => CassinoRoute,
} as any)
const CassinoCrashRoute = CassinoCrashRouteImport.update({
  id: '/crash',
  path: '/crash',
  getParentRoute: () => CassinoRoute,
} as any)
const CassinoOriginaisRoute = CassinoOriginaisRouteImport.update({
  id: '/originais',
  path: '/originais',
  getParentRoute: () => CassinoRoute,
} as any)
const CassinoSlotsRoute = CassinoSlotsRouteImport.update({
  id: '/slots',
  path: '/slots',
  getParentRoute: () => CassinoRoute,
} as any)
const EsportesIndexRoute = EsportesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EsportesRoute,
} as any)
const EsportesAoVivoRoute = EsportesAoVivoRouteImport.update({
  id: '/ao-vivo',
  path: '/ao-vivo',
  getParentRoute: () => EsportesRoute,
} as any)
const EsportesProximosRoute = EsportesProximosRouteImport.update({
  id: '/proximos',
  path: '/proximos',
  getParentRoute: () => EsportesRoute,
} as any)
const PromocoesIndexRoute = PromocoesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PromocoesRoute,
} as any)
const PromocoesIdRoute = PromocoesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PromocoesRoute,
} as any)
const AdminReviewsIndexRoute = AdminReviewsIndexRouteImport.update({
  id: '/reviews/',
  path: '/reviews/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsIdRoute = AdminReviewsIdRouteImport.update({
  id: '/reviews/$id',
  path: '/reviews/$id',
  getParentRoute: () => AdminRoute,
} as any)
const CassinoJogoIdRoute = CassinoJogoIdRouteImport.update({
  id: '/jogo/$id',
  path: '/jogo/$id',
  getParentRoute: () => CassinoRoute,
} as any)
const EsportesEventoIdRoute = EsportesEventoIdRouteImport.update({
  id: '/evento/$id',
  path: '/evento/$id',
  getParentRoute: () => EsportesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/aml': typeof AmlRoute
  '/apostas': typeof ApostasRoute
  '/bonus': typeof BonusRoute
  '/borabet': typeof BorabetRoute
  '/carteira': typeof CarteiraRouteWithChildren
  '/cassino': typeof CassinoRouteWithChildren
  '/contato': typeof ContatoRoute
  '/cookies': typeof CookiesRoute
  '/desafios': typeof DesafiosRoute
  '/esportes': typeof EsportesRouteWithChildren
  '/faq': typeof FaqRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/notificacoes': typeof NotificacoesRoute
  '/onboarding': typeof OnboardingRoute
  '/pesquisa': typeof PesquisaRoute
  '/privacy': typeof PrivacyRoute
  '/promocoes': typeof PromocoesRouteWithChildren
  '/recompensas': typeof RecompensasRoute
  '/register': typeof RegisterRoute
  '/regras-apostas': typeof RegrasApostasRoute
  '/responsible-gambling': typeof ResponsibleGamblingRoute
  '/roleta': typeof RoletaRoute
  '/sobre': typeof SobreRoute
  '/suporte': typeof SuporteRoute
  '/terms': typeof TermsRoute
  '/vip': typeof VipRoute
  '/account/history': typeof AccountHistoryRoute
  '/account/limits': typeof AccountLimitsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/verification': typeof AccountVerificationRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/carteira/deposito': typeof CarteiraDepositoRoute
  '/carteira/saque': typeof CarteiraSaqueRoute
  '/carteira/transacoes': typeof CarteiraTransacoesRoute
  '/cassino/ao-vivo': typeof CassinoAoVivoRoute
  '/cassino/crash': typeof CassinoCrashRoute
  '/cassino/originais': typeof CassinoOriginaisRoute
  '/cassino/slots': typeof CassinoSlotsRoute
  '/esportes/ao-vivo': typeof EsportesAoVivoRoute
  '/esportes/proximos': typeof EsportesProximosRoute
  '/promocoes/$id': typeof PromocoesIdRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/carteira/': typeof CarteiraIndexRoute
  '/cassino/': typeof CassinoIndexRoute
  '/esportes/': typeof EsportesIndexRoute
  '/promocoes/': typeof PromocoesIndexRoute
  '/admin/reviews/$id': typeof AdminReviewsIdRoute
  '/cassino/jogo/$id': typeof CassinoJogoIdRoute
  '/esportes/evento/$id': typeof EsportesEventoIdRoute
  '/admin/reviews/': typeof AdminReviewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aml': typeof AmlRoute
  '/apostas': typeof ApostasRoute
  '/bonus': typeof BonusRoute
  '/borabet': typeof BorabetRoute
  '/contato': typeof ContatoRoute
  '/cookies': typeof CookiesRoute
  '/desafios': typeof DesafiosRoute
  '/faq': typeof FaqRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/notificacoes': typeof NotificacoesRoute
  '/onboarding': typeof OnboardingRoute
  '/pesquisa': typeof PesquisaRoute
  '/privacy': typeof PrivacyRoute
  '/recompensas': typeof RecompensasRoute
  '/register': typeof RegisterRoute
  '/regras-apostas': typeof RegrasApostasRoute
  '/responsible-gambling': typeof ResponsibleGamblingRoute
  '/roleta': typeof RoletaRoute
  '/sobre': typeof SobreRoute
  '/suporte': typeof SuporteRoute
  '/terms': typeof TermsRoute
  '/vip': typeof VipRoute
  '/account/history': typeof AccountHistoryRoute
  '/account/limits': typeof AccountLimitsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/verification': typeof AccountVerificationRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/carteira/deposito': typeof CarteiraDepositoRoute
  '/carteira/saque': typeof CarteiraSaqueRoute
  '/carteira/transacoes': typeof CarteiraTransacoesRoute
  '/cassino/ao-vivo': typeof CassinoAoVivoRoute
  '/cassino/crash': typeof CassinoCrashRoute
  '/cassino/originais': typeof CassinoOriginaisRoute
  '/cassino/slots': typeof CassinoSlotsRoute
  '/esportes/ao-vivo': typeof EsportesAoVivoRoute
  '/esportes/proximos': typeof EsportesProximosRoute
  '/promocoes/$id': typeof PromocoesIdRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/carteira': typeof CarteiraIndexRoute
  '/cassino': typeof CassinoIndexRoute
  '/esportes': typeof EsportesIndexRoute
  '/promocoes': typeof PromocoesIndexRoute
  '/admin/reviews/$id': typeof AdminReviewsIdRoute
  '/cassino/jogo/$id': typeof CassinoJogoIdRoute
  '/esportes/evento/$id': typeof EsportesEventoIdRoute
  '/admin/reviews': typeof AdminReviewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/aml': typeof AmlRoute
  '/apostas': typeof ApostasRoute
  '/bonus': typeof BonusRoute
  '/borabet': typeof BorabetRoute
  '/carteira': typeof CarteiraRouteWithChildren
  '/cassino': typeof CassinoRouteWithChildren
  '/contato': typeof ContatoRoute
  '/cookies': typeof CookiesRoute
  '/desafios': typeof DesafiosRoute
  '/esportes': typeof EsportesRouteWithChildren
  '/faq': typeof FaqRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/notificacoes': typeof NotificacoesRoute
  '/onboarding': typeof OnboardingRoute
  '/pesquisa': typeof PesquisaRoute
  '/privacy': typeof PrivacyRoute
  '/promocoes': typeof PromocoesRouteWithChildren
  '/recompensas': typeof RecompensasRoute
  '/register': typeof RegisterRoute
  '/regras-apostas': typeof RegrasApostasRoute
  '/responsible-gambling': typeof ResponsibleGamblingRoute
  '/roleta': typeof RoletaRoute
  '/sobre': typeof SobreRoute
  '/suporte': typeof SuporteRoute
  '/terms': typeof TermsRoute
  '/vip': typeof VipRoute
  '/account/history': typeof AccountHistoryRoute
  '/account/limits': typeof AccountLimitsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/verification': typeof AccountVerificationRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/carteira/deposito': typeof CarteiraDepositoRoute
  '/carteira/saque': typeof CarteiraSaqueRoute
  '/carteira/transacoes': typeof CarteiraTransacoesRoute
  '/cassino/ao-vivo': typeof CassinoAoVivoRoute
  '/cassino/crash': typeof CassinoCrashRoute
  '/cassino/originais': typeof CassinoOriginaisRoute
  '/cassino/slots': typeof CassinoSlotsRoute
  '/esportes/ao-vivo': typeof EsportesAoVivoRoute
  '/esportes/proximos': typeof EsportesProximosRoute
  '/promocoes/$id': typeof PromocoesIdRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/carteira/': typeof CarteiraIndexRoute
  '/cassino/': typeof CassinoIndexRoute
  '/esportes/': typeof EsportesIndexRoute
  '/promocoes/': typeof PromocoesIndexRoute
  '/admin/reviews/$id': typeof AdminReviewsIdRoute
  '/cassino/jogo/$id': typeof CassinoJogoIdRoute
  '/esportes/evento/$id': typeof EsportesEventoIdRoute
  '/admin/reviews/': typeof AdminReviewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/aml'
    | '/apostas'
    | '/bonus'
    | '/borabet'
    | '/carteira'
    | '/cassino'
    | '/contato'
    | '/cookies'
    | '/desafios'
    | '/esportes'
    | '/faq'
    | '/favoritos'
    | '/login'
    | '/notificacoes'
    | '/onboarding'
    | '/pesquisa'
    | '/privacy'
    | '/promocoes'
    | '/recompensas'
    | '/register'
    | '/regras-apostas'
    | '/responsible-gambling'
    | '/roleta'
    | '/sobre'
    | '/suporte'
    | '/terms'
    | '/vip'
    | '/account/history'
    | '/account/limits'
    | '/account/profile'
    | '/account/security'
    | '/account/verification'
    | '/admin/audit'
    | '/admin/settings'
    | '/admin/users'
    | '/carteira/deposito'
    | '/carteira/saque'
    | '/carteira/transacoes'
    | '/cassino/ao-vivo'
    | '/cassino/crash'
    | '/cassino/originais'
    | '/cassino/slots'
    | '/esportes/ao-vivo'
    | '/esportes/proximos'
    | '/promocoes/$id'
    | '/account/'
    | '/admin/'
    | '/carteira/'
    | '/cassino/'
    | '/esportes/'
    | '/promocoes/'
    | '/admin/reviews/$id'
    | '/cassino/jogo/$id'
    | '/esportes/evento/$id'
    | '/admin/reviews/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aml'
    | '/apostas'
    | '/bonus'
    | '/borabet'
    | '/contato'
    | '/cookies'
    | '/desafios'
    | '/faq'
    | '/favoritos'
    | '/login'
    | '/notificacoes'
    | '/onboarding'
    | '/pesquisa'
    | '/privacy'
    | '/recompensas'
    | '/register'
    | '/regras-apostas'
    | '/responsible-gambling'
    | '/roleta'
    | '/sobre'
    | '/suporte'
    | '/terms'
    | '/vip'
    | '/account/history'
    | '/account/limits'
    | '/account/profile'
    | '/account/security'
    | '/account/verification'
    | '/admin/audit'
    | '/admin/settings'
    | '/admin/users'
    | '/carteira/deposito'
    | '/carteira/saque'
    | '/carteira/transacoes'
    | '/cassino/ao-vivo'
    | '/cassino/crash'
    | '/cassino/originais'
    | '/cassino/slots'
    | '/esportes/ao-vivo'
    | '/esportes/proximos'
    | '/promocoes/$id'
    | '/account'
    | '/admin'
    | '/carteira'
    | '/cassino'
    | '/esportes'
    | '/promocoes'
    | '/admin/reviews/$id'
    | '/cassino/jogo/$id'
    | '/esportes/evento/$id'
    | '/admin/reviews'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/aml'
    | '/apostas'
    | '/bonus'
    | '/borabet'
    | '/carteira'
    | '/cassino'
    | '/contato'
    | '/cookies'
    | '/desafios'
    | '/esportes'
    | '/faq'
    | '/favoritos'
    | '/login'
    | '/notificacoes'
    | '/onboarding'
    | '/pesquisa'
    | '/privacy'
    | '/promocoes'
    | '/recompensas'
    | '/register'
    | '/regras-apostas'
    | '/responsible-gambling'
    | '/roleta'
    | '/sobre'
    | '/suporte'
    | '/terms'
    | '/vip'
    | '/account/history'
    | '/account/limits'
    | '/account/profile'
    | '/account/security'
    | '/account/verification'
    | '/admin/audit'
    | '/admin/settings'
    | '/admin/users'
    | '/carteira/deposito'
    | '/carteira/saque'
    | '/carteira/transacoes'
    | '/cassino/ao-vivo'
    | '/cassino/crash'
    | '/cassino/originais'
    | '/cassino/slots'
    | '/esportes/ao-vivo'
    | '/esportes/proximos'
    | '/promocoes/$id'
    | '/account/'
    | '/admin/'
    | '/carteira/'
    | '/cassino/'
    | '/esportes/'
    | '/promocoes/'
    | '/admin/reviews/$id'
    | '/cassino/jogo/$id'
    | '/esportes/evento/$id'
    | '/admin/reviews/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AmlRoute: typeof AmlRoute
  ApostasRoute: typeof ApostasRoute
  BonusRoute: typeof BonusRoute
  BorabetRoute: typeof BorabetRoute
  CarteiraRoute: typeof CarteiraRouteWithChildren
  CassinoRoute: typeof CassinoRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  CookiesRoute: typeof CookiesRoute
  DesafiosRoute: typeof DesafiosRoute
  EsportesRoute: typeof EsportesRouteWithChildren
  FaqRoute: typeof FaqRoute
  FavoritosRoute: typeof FavoritosRoute
  LoginRoute: typeof LoginRoute
  NotificacoesRoute: typeof NotificacoesRoute
  OnboardingRoute: typeof OnboardingRoute
  PesquisaRoute: typeof PesquisaRoute
  PrivacyRoute: typeof PrivacyRoute
  PromocoesRoute: typeof PromocoesRouteWithChildren
  RecompensasRoute: typeof RecompensasRoute
  RegisterRoute: typeof RegisterRoute
  RegrasApostasRoute: typeof RegrasApostasRoute
  ResponsibleGamblingRoute: typeof ResponsibleGamblingRoute
  RoletaRoute: typeof RoletaRoute
  SobreRoute: typeof SobreRoute
  SuporteRoute: typeof SuporteRoute
  TermsRoute: typeof TermsRoute
  VipRoute: typeof VipRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aml': {
      id: '/aml'
      path: '/aml'
      fullPath: '/aml'
      preLoaderRoute: typeof AmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apostas': {
      id: '/apostas'
      path: '/apostas'
      fullPath: '/apostas'
      preLoaderRoute: typeof ApostasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bonus': {
      id: '/bonus'
      path: '/bonus'
      fullPath: '/bonus'
      preLoaderRoute: typeof BonusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/borabet': {
      id: '/borabet'
      path: '/borabet'
      fullPath: '/borabet'
      preLoaderRoute: typeof BorabetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carteira': {
      id: '/carteira'
      path: '/carteira'
      fullPath: '/carteira'
      preLoaderRoute: typeof CarteiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cassino': {
      id: '/cassino'
      path: '/cassino'
      fullPath: '/cassino'
      preLoaderRoute: typeof CassinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desafios': {
      id: '/desafios'
      path: '/desafios'
      fullPath: '/desafios'
      preLoaderRoute: typeof DesafiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esportes': {
      id: '/esportes'
      path: '/esportes'
      fullPath: '/esportes'
      preLoaderRoute: typeof EsportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisa': {
      id: '/pesquisa'
      path: '/pesquisa'
      fullPath: '/pesquisa'
      preLoaderRoute: typeof PesquisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promocoes': {
      id: '/promocoes'
      path: '/promocoes'
      fullPath: '/promocoes'
      preLoaderRoute: typeof PromocoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recompensas': {
      id: '/recompensas'
      path: '/recompensas'
      fullPath: '/recompensas'
      preLoaderRoute: typeof RecompensasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regras-apostas': {
      id: '/regras-apostas'
      path: '/regras-apostas'
      fullPath: '/regras-apostas'
      preLoaderRoute: typeof RegrasApostasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responsible-gambling': {
      id: '/responsible-gambling'
      path: '/responsible-gambling'
      fullPath: '/responsible-gambling'
      preLoaderRoute: typeof ResponsibleGamblingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roleta': {
      id: '/roleta'
      path: '/roleta'
      fullPath: '/roleta'
      preLoaderRoute: typeof RoletaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vip': {
      id: '/vip'
      path: '/vip'
      fullPath: '/vip'
      preLoaderRoute: typeof VipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/history': {
      id: '/account/history'
      path: '/history'
      fullPath: '/account/history'
      preLoaderRoute: typeof AccountHistoryRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/limits': {
      id: '/account/limits'
      path: '/limits'
      fullPath: '/account/limits'
      preLoaderRoute: typeof AccountLimitsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/security': {
      id: '/account/security'
      path: '/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AccountSecurityRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/verification': {
      id: '/account/verification'
      path: '/verification'
      fullPath: '/account/verification'
      preLoaderRoute: typeof AccountVerificationRouteImport
      parentRoute: typeof AccountRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/carteira/': {
      id: '/carteira/'
      path: '/'
      fullPath: '/carteira/'
      preLoaderRoute: typeof CarteiraIndexRouteImport
      parentRoute: typeof CarteiraRoute
    }
    '/carteira/deposito': {
      id: '/carteira/deposito'
      path: '/deposito'
      fullPath: '/carteira/deposito'
      preLoaderRoute: typeof CarteiraDepositoRouteImport
      parentRoute: typeof CarteiraRoute
    }
    '/carteira/saque': {
      id: '/carteira/saque'
      path: '/saque'
      fullPath: '/carteira/saque'
      preLoaderRoute: typeof CarteiraSaqueRouteImport
      parentRoute: typeof CarteiraRoute
    }
    '/carteira/transacoes': {
      id: '/carteira/transacoes'
      path: '/transacoes'
      fullPath: '/carteira/transacoes'
      preLoaderRoute: typeof CarteiraTransacoesRouteImport
      parentRoute: typeof CarteiraRoute
    }
    '/cassino/': {
      id: '/cassino/'
      path: '/'
      fullPath: '/cassino/'
      preLoaderRoute: typeof CassinoIndexRouteImport
      parentRoute: typeof CassinoRoute
    }
    '/cassino/ao-vivo': {
      id: '/cassino/ao-vivo'
      path: '/ao-vivo'
      fullPath: '/cassino/ao-vivo'
      preLoaderRoute: typeof CassinoAoVivoRouteImport
      parentRoute: typeof CassinoRoute
    }
    '/cassino/crash': {
      id: '/cassino/crash'
      path: '/crash'
      fullPath: '/cassino/crash'
      preLoaderRoute: typeof CassinoCrashRouteImport
      parentRoute: typeof CassinoRoute
    }
    '/cassino/originais': {
      id: '/cassino/originais'
      path: '/originais'
      fullPath: '/cassino/originais'
      preLoaderRoute: typeof CassinoOriginaisRouteImport
      parentRoute: typeof CassinoRoute
    }
    '/cassino/slots': {
      id: '/cassino/slots'
      path: '/slots'
      fullPath: '/cassino/slots'
      preLoaderRoute: typeof CassinoSlotsRouteImport
      parentRoute: typeof CassinoRoute
    }
    '/esportes/': {
      id: '/esportes/'
      path: '/'
      fullPath: '/esportes/'
      preLoaderRoute: typeof EsportesIndexRouteImport
      parentRoute: typeof EsportesRoute
    }
    '/esportes/ao-vivo': {
      id: '/esportes/ao-vivo'
      path: '/ao-vivo'
      fullPath: '/esportes/ao-vivo'
      preLoaderRoute: typeof EsportesAoVivoRouteImport
      parentRoute: typeof EsportesRoute
    }
    '/esportes/proximos': {
      id: '/esportes/proximos'
      path: '/proximos'
      fullPath: '/esportes/proximos'
      preLoaderRoute: typeof EsportesProximosRouteImport
      parentRoute: typeof EsportesRoute
    }
    '/promocoes/': {
      id: '/promocoes/'
      path: '/'
      fullPath: '/promocoes/'
      preLoaderRoute: typeof PromocoesIndexRouteImport
      parentRoute: typeof PromocoesRoute
    }
    '/promocoes/$id': {
      id: '/promocoes/$id'
      path: '/$id'
      fullPath: '/promocoes/$id'
      preLoaderRoute: typeof PromocoesIdRouteImport
      parentRoute: typeof PromocoesRoute
    }
    '/admin/reviews/': {
      id: '/admin/reviews/'
      path: '/reviews'
      fullPath: '/admin/reviews/'
      preLoaderRoute: typeof AdminReviewsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews/$id': {
      id: '/admin/reviews/$id'
      path: '/reviews/$id'
      fullPath: '/admin/reviews/$id'
      preLoaderRoute: typeof AdminReviewsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/cassino/jogo/$id': {
      id: '/cassino/jogo/$id'
      path: '/jogo/$id'
      fullPath: '/cassino/jogo/$id'
      preLoaderRoute: typeof CassinoJogoIdRouteImport
      parentRoute: typeof CassinoRoute
    }
    '/esportes/evento/$id': {
      id: '/esportes/evento/$id'
      path: '/evento/$id'
      fullPath: '/esportes/evento/$id'
      preLoaderRoute: typeof EsportesEventoIdRouteImport
      parentRoute: typeof EsportesRoute
    }
  }
}

interface AccountRouteChildren {
  AccountHistoryRoute: typeof AccountHistoryRoute
  AccountLimitsRoute: typeof AccountLimitsRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountSecurityRoute: typeof AccountSecurityRoute
  AccountVerificationRoute: typeof AccountVerificationRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountHistoryRoute: AccountHistoryRoute,
  AccountLimitsRoute: AccountLimitsRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountSecurityRoute: AccountSecurityRoute,
  AccountVerificationRoute: AccountVerificationRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminReviewsIdRoute: typeof AdminReviewsIdRoute
  AdminReviewsIndexRoute: typeof AdminReviewsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminReviewsIdRoute: AdminReviewsIdRoute,
  AdminReviewsIndexRoute: AdminReviewsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CarteiraRouteChildren {
  CarteiraDepositoRoute: typeof CarteiraDepositoRoute
  CarteiraSaqueRoute: typeof CarteiraSaqueRoute
  CarteiraTransacoesRoute: typeof CarteiraTransacoesRoute
  CarteiraIndexRoute: typeof CarteiraIndexRoute
}

const CarteiraRouteChildren: CarteiraRouteChildren = {
  CarteiraDepositoRoute: CarteiraDepositoRoute,
  CarteiraSaqueRoute: CarteiraSaqueRoute,
  CarteiraTransacoesRoute: CarteiraTransacoesRoute,
  CarteiraIndexRoute: CarteiraIndexRoute,
}

const CarteiraRouteWithChildren = CarteiraRoute._addFileChildren(
  CarteiraRouteChildren,
)

interface CassinoRouteChildren {
  CassinoAoVivoRoute: typeof CassinoAoVivoRoute
  CassinoCrashRoute: typeof CassinoCrashRoute
  CassinoOriginaisRoute: typeof CassinoOriginaisRoute
  CassinoSlotsRoute: typeof CassinoSlotsRoute
  CassinoIndexRoute: typeof CassinoIndexRoute
  CassinoJogoIdRoute: typeof CassinoJogoIdRoute
}

const CassinoRouteChildren: CassinoRouteChildren = {
  CassinoAoVivoRoute: CassinoAoVivoRoute,
  CassinoCrashRoute: CassinoCrashRoute,
  CassinoOriginaisRoute: CassinoOriginaisRoute,
  CassinoSlotsRoute: CassinoSlotsRoute,
  CassinoIndexRoute: CassinoIndexRoute,
  CassinoJogoIdRoute: CassinoJogoIdRoute,
}

const CassinoRouteWithChildren =
  CassinoRoute._addFileChildren(CassinoRouteChildren)

interface EsportesRouteChildren {
  EsportesAoVivoRoute: typeof EsportesAoVivoRoute
  EsportesProximosRoute: typeof EsportesProximosRoute
  EsportesIndexRoute: typeof EsportesIndexRoute
  EsportesEventoIdRoute: typeof EsportesEventoIdRoute
}

const EsportesRouteChildren: EsportesRouteChildren = {
  EsportesAoVivoRoute: EsportesAoVivoRoute,
  EsportesProximosRoute: EsportesProximosRoute,
  EsportesIndexRoute: EsportesIndexRoute,
  EsportesEventoIdRoute: EsportesEventoIdRoute,
}

const EsportesRouteWithChildren = EsportesRoute._addFileChildren(
  EsportesRouteChildren,
)

interface PromocoesRouteChildren {
  PromocoesIdRoute: typeof PromocoesIdRoute
  PromocoesIndexRoute: typeof PromocoesIndexRoute
}

const PromocoesRouteChildren: PromocoesRouteChildren = {
  PromocoesIdRoute: PromocoesIdRoute,
  PromocoesIndexRoute: PromocoesIndexRoute,
}

const PromocoesRouteWithChildren = PromocoesRoute._addFileChildren(
  PromocoesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AmlRoute: AmlRoute,
  ApostasRoute: ApostasRoute,
  BonusRoute: BonusRoute,
  BorabetRoute: BorabetRoute,
  CarteiraRoute: CarteiraRouteWithChildren,
  CassinoRoute: CassinoRouteWithChildren,
  ContatoRoute: ContatoRoute,
  CookiesRoute: CookiesRoute,
  DesafiosRoute: DesafiosRoute,
  EsportesRoute: EsportesRouteWithChildren,
  FaqRoute: FaqRoute,
  FavoritosRoute: FavoritosRoute,
  LoginRoute: LoginRoute,
  NotificacoesRoute: NotificacoesRoute,
  OnboardingRoute: OnboardingRoute,
  PesquisaRoute: PesquisaRoute,
  PrivacyRoute: PrivacyRoute,
  PromocoesRoute: PromocoesRouteWithChildren,
  RecompensasRoute: RecompensasRoute,
  RegisterRoute: RegisterRoute,
  RegrasApostasRoute: RegrasApostasRoute,
  ResponsibleGamblingRoute: ResponsibleGamblingRoute,
  RoletaRoute: RoletaRoute,
  SobreRoute: SobreRoute,
  SuporteRoute: SuporteRoute,
  TermsRoute: TermsRoute,
  VipRoute: VipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
